function BD2 = fn_2S(dist_x_pl,uold_nu)
BD2 = (1./( ((dist_x_pl+ circshift(dist_x_pl,1))./dist_x_pl).^2 .*(-dist_x_pl) - (-dist_x_pl - circshift(dist_x_pl,1))   ))...
    .* (((dist_x_pl+ circshift(dist_x_pl,1))./dist_x_pl).^2 .*circshift(uold_nu,1) - circshift(uold_nu,2) - ...
    (((dist_x_pl+ circshift(dist_x_pl,1))./dist_x_pl).^2 -1).*uold_nu);
end
